[package]
name = "wordle-rust"
version = "0.1.0"
authors = ["notken12"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
ansi_term = "0.12"